library(tidyverse)
library(ggplot2)
library(corrplot)
df <- read.csv('NY Realstate Pricing.csv')
df
dim(df)
head(df)
names(df)
str(df)
summary(df)
colSums(is.na(df))
sum(is.na(df))
length(unique(df$F1))
table(df$room_type)
df <- df %>% select(-F1, -id)
dim(df)
for (col in names(df)) {
  unique_vals <- unique(df[[col]])
  print(paste0('Unique values in column ', col, ': ', unique_vals))
}
for (column in names(df)) {
  unique_values <- n_distinct(df[[column]])
  value_counts <- table(df[[column]])
  print(paste0('Column name: ', column))
  print(paste0('Number of unique values: ', unique_values))
  print(paste0('Value counts: \n', value_counts, '\n'))
}
sum(duplicated(df))
ggplot(df, aes(x = price)) + geom_histogram(bins = 50) + ggtitle('Grafico do preço')
ggplot(df, aes(x = room_type)) + geom_bar() + ggtitle('Room types')
ggplot(df, aes(x = minimum_nights, y = price)) + geom_point() + ggtitle('Preço x Noites minimas')
coor <- cor(df)
corrplot(coor, method = 'number', type = 'upper', tl.col = 'black', tl.srt = 45)
install.packages('DataExplorer')
library(DataExplorer)
plot_intro(df)
